name: Package Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
              php: [7.3, 7.4, 8.0]
              laravel: [7.*, 8.*]
              dependency-version: [prefer-stable]
              include:
                - laravel: 7.*
                  testbench: 5.*
                - laravel: 8.*
                  testbench: 6.*
        name: PHP${{ matrix.php }} - LARAVEL${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none
                  tools: composer:v2

            - name: Install PHP 7 dependencies
              run: |
                composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
              if: "matrix.php < 8"

            - name: Install PHP 8 dependencies
              run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-interaction --no-progress
              if: "matrix.php >= 8"

            - name: Execute tests
              run: vendor/bin/phpunit